# Generated by Django 3.2.13 on 2022-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_docs', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('file_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
