# Generated by Django 3.2.13 on 2022-06-04 10:41

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_docs',
            field=models.FileField(upload_to=uploader.models.create_name),
        ),
    ]
